In [1]:
import torch

In [2]:
x = torch.empty(5,3)

In [3]:
x = torch.empty(5,3, dtype=torch.float32)   # 新建一个空的，数据都是随机值，每次都会变
print(x)

tensor([[9.2755e-39, 1.0561e-38, 5.0511e-39],
        [5.0510e-39, 4.2246e-39, 1.0286e-38],
        [1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39],
        [8.7245e-39, 9.2755e-39, 8.9082e-39]])


In [4]:
x.half()  # 将数据变为半精度

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)

In [5]:
y = torch.rand(5,3, dtype=torch.float32)
print(y)

tensor([[0.3620, 0.5660, 0.7610],
        [0.7748, 0.9409, 0.4492],
        [0.0780, 0.8547, 0.2295],
        [0.6775, 0.1408, 0.3257],
        [0.4907, 0.2096, 0.5018]])


In [6]:
y.half()

tensor([[0.3621, 0.5659, 0.7607],
        [0.7749, 0.9409, 0.4492],
        [0.0780, 0.8545, 0.2295],
        [0.6777, 0.1407, 0.3257],
        [0.4907, 0.2096, 0.5020]], dtype=torch.float16)

In [7]:
zeroTensor = torch.zeros(5,3, dtype=torch.float16)
print(zeroTensor)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)


In [8]:
fromLstTensor = torch.tensor([1.2, 3.0, 4, 0], dtype=torch.float16)
print(fromLstTensor)

tensor([1.2002, 3.0000, 4.0000, 0.0000], dtype=torch.float16)


In [9]:
fromTensorTensor = y.new_ones(3,3)
print(fromTensorTensor, fromTensorTensor.dtype)

fromTensorTensor2 = y.new_ones(3,3,dtype=torch.float16)
print(fromTensorTensor2, fromTensorTensor2.dtype)

fromTensorTensor3 = torch.randn_like(y, dtype=torch.float64)
print(fromTensorTensor3, fromTensorTensor3.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])torch.float32
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)torch.float16
tensor([[-0.3025, -1.2338,  0.8515],
        [-0.0760,  0.3108, -0.3506],
        [-1.2476,  1.3294,  0.1484],
        [ 1.9713, -1.5333,  0.0382],
        [ 1.7524,  0.7143,  0.9952]], dtype=torch.float64)torch.float64


In [10]:
print(zeroTensor.shape,  zeroTensor.size())
print(fromTensorTensor.shape, fromTensorTensor.size())  # torch.Size 是一个封装过的Tuple

torch.Size([5, 3])torch.Size([5, 3])
torch.Size([3, 3])torch.Size([3, 3])


In [11]:
print(fromTensorTensor)
fromTensorTensor = fromTensorTensor.type(fromTensorTensor2.dtype).cuda()
addTensor = fromTensorTensor + fromTensorTensor2.cuda()        # dtype类型不一致不能操作， 且float16只支持GPU版本
addTensor2 = torch.add(fromTensorTensor, fromTensorTensor2.cuda())
fromTensorTensor.add_(fromTensorTensor2.cuda())                # pytorch的inplace操作后面都加这_
print(addTensor,'\n\n', addTensor2,'\n\n', fromTensorTensor)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], device='cuda:0', dtype=torch.float16)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], device='cuda:0', dtype=torch.float16)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], device='cuda:0', dtype=torch.float16)


In [12]:
m = x[2,:]  # pytorch中索引结果与原数据共享内存，修改其中一个另外一个也会同样变化
print(m)
print(x)
m += 1
print(x)
x -= 1
print(m)

tensor([1.0653e-38, 1.0194e-38, 8.4490e-39])
tensor([[9.2755e-39, 1.0561e-38, 5.0511e-39],
        [5.0510e-39, 4.2246e-39, 1.0286e-38],
        [1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39],
        [8.7245e-39, 9.2755e-39, 8.9082e-39]])
tensor([[9.2755e-39, 1.0561e-38, 5.0511e-39],
        [5.0510e-39, 4.2246e-39, 1.0286e-38],
        [1.0000e+00, 1.0000e+00, 1.0000e+00],
        [1.0469e-38, 9.3674e-39, 9.9184e-39],
        [8.7245e-39, 9.2755e-39, 8.9082e-39]])
tensor([0., 0., 0.])


In [13]:
print(torch.masked_select(x, x>0.5))

tensor([])


In [14]:
# view返回的新tensor与原tensor共享内存，修改一个另外一个也变化。 view只是改变张量的观察角度而已
# reshape有可能会返回一个拷贝，但不一定啊：  需要不共享内存的数据：建议先clone后view
viewX = x.view(15)
print(viewX)
viewX2 = x.view(-1,5)
print(viewX2)
print(viewX.size(), viewX2.size(), x.size())

x += 1
print(x,'\n', viewX, '\n', viewX2)

tensor([-1., -1., -1., -1., -1., -1.,  0.,  0.,  0., -1., -1., -1., -1., -1.,
        -1.])
tensor([[-1., -1., -1., -1., -1.],
        [-1.,  0.,  0.,  0., -1.],
        [-1., -1., -1., -1., -1.]])
torch.Size([15])torch.Size([3, 5])torch.Size([5, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0.])
tensor([[0., 0., 0., 0., 0.],
        [0., 1., 1., 1., 0.],
        [0., 0., 0., 0., 0.]])


In [15]:
itemTensor = torch.randn(1)
print(itemTensor)
print(itemTensor.item())  # 可以将标量Tensor转为一个python number

tensor([0.0467])
0.04670458659529686


In [16]:
# pytorch支持线性代数操作
print(viewX2)
print(torch.trace(viewX2))
print(torch.diag(viewX2))
print(torch.t(viewX2))

tensor([[0., 0., 0., 0., 0.],
        [0., 1., 1., 1., 0.],
        [0., 0., 0., 0., 0.]])
tensor(1.)
tensor([0., 1., 0.])
tensor([[0., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 0., 0.]])


In [17]:
# pytorch广播机制：适当复制元素使得两个Tensor形状形同后再按元素运算
t1 = torch.arange(1,3).view(1,2)
t2 = torch.arange(1,4).view(3,1)
print(t1, t2)
broadAdd = t1 + t2
print(broadAdd, '\n', broadAdd.shape)

tensor([[1, 2]])tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])
torch.Size([3, 2])


In [18]:
# 运算的内存开销 : += add_ [:] 可以避免重开内存空间
beforeT1Id = id(t1)
t1 = t1 + t2     # 开辟新内存了
print(id(t1) == beforeT1Id)

beforeT1Id = id(t1)
t1[:] = t1 + t2  # 使用[:]将加法结果写入了t1对应的内存中，避免了内存开销
print(id(t1) == beforeT1Id)

beforeT1Id = id(t1)
t1 += t2         # 使用+=将加法结果写入了t1对应的内存中，避免了内存开销
print(id(t1) == beforeT1Id)

beforeT1Id = id(t1)
t1.add_(t2)      # 使用add_将加法结果写入了t1对应的内存中，避免了内存开销
print(id(t1) == beforeT1Id)


False
True
True
True


In [19]:
# Tensor与Numpy的相互转换
npT1 = t1.numpy()              # 将Tensor转为array, 共享内存
print(npT1, '\n', t1)
npT1 += 1
print(npT1, '\n', t1)

tT2 = torch.from_numpy(npT1)   # 将array转为tensor，共享内存
print(npT1, '\n', tT2)
tT2 -= 4
print(npT1, '\n', tT2)

# 使用torch.tensor()来转化array的话，内存不共享，总是进行数据拷贝


[[ 5  6]
 [ 9 10]
 [13 14]]
tensor([[ 5,  6],
        [ 9, 10],
        [13, 14]])
[[ 6  7]
 [10 11]
 [14 15]]
tensor([[ 6,  7],
        [10, 11],
        [14, 15]])
[[ 6  7]
 [10 11]
 [14 15]]
tensor([[ 6,  7],
        [10, 11],
        [14, 15]])
[[ 2  3]
 [ 6  7]
 [10 11]]
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


In [20]:
print(torch.cuda.is_available())
device = torch.device('cuda')
cudaT1 = torch.ones_like(t1, device=device)   #在GPU上新建一个变量
print(cudaT1)

t1 = t1.to(device, dtype=torch.float16)       # .to函数可以同时修改对应的dtype
cudaT2 = cudaT1.type(torch.float16) + t1
print(cudaT2, '\n', cudaT2.to('cpu', torch.double))


True
tensor([[1, 1],
        [1, 1],
        [1, 1]], device='cuda:0')
tensor([[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]], device='cuda:0', dtype=torch.float16)
tensor([[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]], dtype=torch.float64)


In [21]:
print(cudaT2.requires_grad)  # cudaT2的requires_grad属性设置为True，将会追踪在当前Tensor上的所有操作
# 设置好前向计算后，只需要使用.backward()即可完成所有的梯度计算，Tensor的梯度会累积到.grad属性中
cudaT2.requires_grad_(True)   # 修改属性
print(cudaT2.requires_grad)

False
True


In [22]:
bpTensor = torch.ones(6,6, requires_grad=True)
print(bpTensor)
print(bpTensor.grad_fn, '\n', bpTensor.is_leaf)         # 直接创建的tensor称为叶子节点，对应的grad_fn为None

funcBpTensor = bpTensor + 2
print(funcBpTensor)
print(funcBpTensor.grad_fn, '\n', funcBpTensor.requires_grad)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]], requires_grad=True)
None
True
tensor([[3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3.]], grad_fn=<AddBackward0>)
True


In [23]:
bpTensor2 = bpTensor * bpTensor * 3
bpTensor3 = bpTensor2.mean().detach()
print(bpTensor2, '\n', bpTensor3)
bpTensor2.backward(torch.ones_like(bpTensor), retain_graph=True)               # 因为bpTensor3是一个标量，所以在调用backward时不需要指定求导变量
# bpTensor3.backward(torch.tensor(1.))                    # RuntimeError：因为detach了
print(bpTensor.grad)
bpTensor2.sum().backward()
print(bpTensor.grad)

tensor([[3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3.]], grad_fn=<MulBackward0>)
tensor(3.)
tensor([[6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6.]])
tensor([[12., 12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12., 12.]])


In [24]:
# 终端梯度追踪栗子
x = torch.tensor(1.0, requires_grad=True)
y1 = x ** 2
with torch.no_grad():
    y2 = x ** 3
y3 = y2 + y1
print(x.requires_grad)
print(y1, y1.requires_grad)
print(y2, y2.requires_grad)
print(y3, y3.requires_grad)

y1.backward(retain_graph=True)
print(x.grad)

x.grad.data.zero_()    # 因为grad会累积，所以在每次反向传播之前都要梯度清零
y3.backward()
print(x.grad)



True
tensor(1., grad_fn=<PowBackward0>)True
tensor(1.)False
tensor(2., grad_fn=<AddBackward0>)True
tensor(2.)
tensor(2.)


In [25]:
a = torch.rand(2,2, dtype=torch.float32)
b = torch.arange(1,19,2, dtype=torch.float32)
c = torch.linspace(1,19,20, dtype=torch.float32)
print(a, '\n', b, '\n', c)

tensor([[0.0198, 0.8136],
        [0.8066, 0.9191]])
tensor([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17.])
tensor([ 1.0000,  1.9474,  2.8947,  3.8421,  4.7895,  5.7368,  6.6842,  7.6316,
         8.5789,  9.5263, 10.4737, 11.4211, 12.3684, 13.3158, 14.2632, 15.2105,
        16.1579, 17.1053, 18.0526, 19.0000])


In [26]:
d = c.view(2,10)
print(d)
print(c.shape, d.shape)

tensor([[ 1.0000,  1.9474,  2.8947,  3.8421,  4.7895,  5.7368,  6.6842,  7.6316,
          8.5789,  9.5263],
        [10.4737, 11.4211, 12.3684, 13.3158, 14.2632, 15.2105, 16.1579, 17.1053,
         18.0526, 19.0000]])
torch.Size([20])torch.Size([2, 10])


In [28]:
##############  新建torch模型，torch.nn：核心数据结构是Module
from torch import nn
#1：
net1 = nn.Sequential(nn.Linear(10, 1))
print(net1, net1[0])

#2
net2 = nn.Sequential()
net2.add_module('linear', nn.Linear(10, 1))
print(net2, net2[0])

#3
from collections import OrderedDict
net3 = nn.Sequential(OrderedDict([('linear', nn.Linear(10,1))]))
print(net3, net3[0])

Sequential(
  (0): Linear(in_features=10, out_features=1, bias=True)
)Linear(in_features=10, out_features=1, bias=True)
Sequential(
  (linear): Linear(in_features=10, out_features=1, bias=True)
)Linear(in_features=10, out_features=1, bias=True)
Sequential(
  (linear): Linear(in_features=10, out_features=1, bias=True)
)Linear(in_features=10, out_features=1, bias=True)


In [36]:
nn.init.normal_(net3[0].weight, mean=0, std=0.01)  # 为权重赋值
net3[0].bias.data.fill_(0)                         # 为bias赋值
for param in net3.parameters(): print(param)

Parameter containing:
tensor([[ 0.0047, -0.0085, -0.0022,  0.0012,  0.0083, -0.0067, -0.0065, -0.0047,
          0.0020, -0.0090]], requires_grad=True)
Parameter containing:
tensor([0.], requires_grad=True)


In [37]:
for layer in net3: print(layer)

Linear(in_features=10, out_features=1, bias=True)


In [ ]:
# torch.optim 提供了很多的模型优化算法：SGD/Adam/RMSProp
import 